import React from 'react'
import { LockKeyhole, ShieldCheck } from 'lucide-react'
import type { CapabilityGrant, PackageManifest } from './skill-runtime.types'

export function SkillCapabilityPanel({ manifest, grants, onApprove, onReject }: { manifest?: PackageManifest; grants: CapabilityGrant[]; onApprove?: (grant: CapabilityGrant) => void; onReject?: (grant: CapabilityGrant) => void }) {
  const requested = manifest?.requestedCapabilities ?? []
  const grantByCapability = new Map(grants.map((grant) => [grant.capability, grant]))
  return <section className="skills-center-subpanel" aria-labelledby="skills-capability-panel-title"><div className="skills-center-subpanel-head"><div><h3 id="skills-capability-panel-title">Capabilities / Grants</h3><p>权限请求必须显示 scope；批准、拒绝和撤销都属于可审计危险操作。</p></div><LockKeyhole size={15} aria-hidden="true" /></div>{requested.length === 0 && grants.length === 0 ? <p className="skills-muted">Manifest 未声明能力请求。</p> : <div className="skills-center-capability-list">{requested.map((item) => { const grant = grantByCapability.get(item.capability); const state = grant?.status || 'requested'; return <div className="skills-center-capability-row" key={item.capability}><div><strong>{item.capability}</strong><small>{scopeSummary(item.scope)}</small></div><span className={'skills-status ' + (state === 'approved' ? 'success' : state === 'rejected' ? 'danger' : 'warning')}>{state}</span>{grant && state === 'requested' && <span className="skills-center-actions"><button type="button" className="skills-text-button" onClick={() => onApprove?.(grant)}>批准</button><button type="button" className="skills-text-button danger" onClick={() => onReject?.(grant)}>拒绝</button></span>}</div>})}{grants.filter((grant) => !requested.some((item) => item.capability === grant.capability)).map((grant) => <div className="skills-center-capability-row" key={grant.id}><div><strong>{grant.capability}</strong><small>{scopeSummary(grant.scope)}</small></div><span className="skills-status info">{grant.status || 'granted'}</span></div>)}</div>}<div className="skills-center-inline-note"><ShieldCheck size={14} aria-hidden="true" /> UI 只发起 store action，不直接拼接 API URL。</div></section>
}

function scopeSummary(scope: Record<string, unknown>) { const entries = Object.entries(scope); return entries.length ? entries.map(([key, value]) => `${key}: ${Array.isArray(value) ? value.join(', ') : String(value)}`).join(' · ') : '未限定 scope' }
